inherit_from:
  - .rubocop_ruby.yml
  - .rubocop_rails.yml

RSpec/DescribeClass:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false

RSpec/RepeatedExampleGroupDescription:
  Exclude:
    - "spec/system/decidim/admin/admin_creates_wallet_spec.rb"

RSpec/RepeatedExampleGroupBody:
  Exclude:
    - "spec/system/decidim/admin/admin_creates_wallet_spec.rb"
