---

base_locale: en
locales: [ en ]

ignore_unused:
  - "activemodel.attributes.election.{description,end_time,secret_until_the_end,start_time,stream_uri,title}"
  - "activemodel.errors.models.election.attributes.attachment.needs_to_be_reattached"
  - "decidim.components.vocdoni.settings.{global,step}.announcement"
  - "decidim.components.vocdoni.name"
  - "decidim.events.vocdoni.election_published.{email_intro,email_outro,email_subject,notification_title}"
  - "decidim.statistics.elections_count"
  - "decidim.vocdoni.admin.wallets.ready.title"
  - "decidim.vocdoni.admin_log.election.{create,delete,end_vote,publish,publish_results,setup,start_vote,unpublish,update}"
  - "decidim.vocdoni.admin_log.wallet.create"
  - "decidim.vocdoni.admin.census.create.{error,success.generate,success.import}"
  - "decidim.vocdoni.election_m.badge_name.{finished,ongoing,upcoming,paused,canceled}"
  - "decidim.vocdoni.election_m.questions"
  - "decidim.vocdoni.elections.show.action_button.{change_vote,vote,vote_again}"
  - "decidim.vocdoni.elections.show.preview"
  - "decidim.vocdoni.elections.show.verify.{already_voted,verify_here,will_verify}"
  - "decidim.vocdoni.votes.check_census.{access,close_modal,election_not_open,failed,form_title}"
  - "decidim.vocdoni.votes.new.can_vote_again"
  - "decidim.vocdoni.votes.new.can_vote_one_more_time"
  - "decidim.vocdoni.votes.new.no_more_votes_left"
  - "decidim.vocdoni.models.answer.fields.proposals"
  - "decidim.vocdoni.admin.elections.new.basic_info"
  - "decidim.vocdoni.admin.elections.new.census"
  - "decidim.vocdoni.admin.elections.new.publish"
  - "decidim.vocdoni.admin.elections.new.questions"
  - "decidim.vocdoni.admin.elections.new.results"
  - "decidim.vocdoni.admin.steps.danger_zone.action.{paused,start,created,vote}"
  - "decidim.vocdoni.elections.election_m.badge_name.canceled"
  - "decidim.vocdoni.elections.election_m.badge_name.finished"
  - "decidim.vocdoni.elections.election_m.badge_name.ongoing"
  - "decidim.vocdoni.elections.election_m.badge_name.paused"
  - "decidim.vocdoni.elections.election_m.badge_name.upcoming"
  - "decidim.vocdoni.elections.elections.filters.canceled"
  - "decidim.vocdoni.elections.elections.filters.date"
  - "decidim.vocdoni.elections.elections.filters.paused"
  - "decidim.vocdoni.elections.orders.label"
  - "decidim.vocdoni.elections.orders.older"
  - "decidim.vocdoni.elections.orders.recent"
  - "decidim.vocdoni.votes.confirm.answer"
  - "decidim.vocdoni.votes.header.confirm"
  - "decidim.vocdoni.votes.header.failed"
  - "decidim.vocdoni.votes.header.login"
  - "decidim.vocdoni.votes.header.submitting"
  - "decidim.vocdoni.votes.header.vote_cast"
  # To be removed once the header image is no longer necessary by the Vocdoni SDK
  - "decidim.admin.shared.gallery.gallery_legend"

ignore_missing:
  - "decidim.participatory_processes.scopes.global"
  - "decidim.vocdoni.admin.census.process_form.error"
  - "decidim.vocdoni.admin.census.success_message_for.success.{generate,import}"
