name: "[CI] Lint"

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUBY_VERSION: 3.0.5
  NODE_VERSION: 16.9.1

jobs:
  lint-report:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # - uses: actions/setup-node@master
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}

      # - name: Get npm cache directory path
      #   id: npm-cache-dir-path
      #   run: echo "::set-output name=dir::$(npm get cache)-vocdoni"

      # - uses: actions/cache@v2
      #   id: npm-cache
      #   with:
      #     path: ${{ steps.npm-cache-dir-path.outputs.dir }}
      #     key: npm-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       npm-

      # - run: npm run lint
      #   name: Lint JS files

      - run: npm run stylelint
        name: Lint SCSS files

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - run: bundle exec rubocop -P
        name: Lint Ruby files

      - run: bundle exec erblint app/**/*.erb
        name: Lint ERB files